## YAML Template.
---

sudo : required
services :
    - docker
    
before_install:
    - docker build -t abdoul-hub/test-gitactions -f Dockerfile.dev .
    
script:
    - docker run abdoul-hub/test-gitactions -d
