## YAML Template.
---

sudo : required
services :
    - docker
    
before_install:
    - docker build -t cabraltogola/test-github-actions
    
script:
    - docker run cabraltogola/test-github-actions
