## YAML Template.
---

sudo : true
language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'

services :
    - docker
    
before_install:
    - docker build -t abdoul-hub/test-gitactions -f Dockerfile.dev .
    
script:
    - docker run -d abdoul-hub/test-gitactions 
    
deploy:
    provider : elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket: "elasticbeanstalk-us-east-2-644809867003"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
    bucket_path: "docker"   
    on:
        branch: main  
    