## YAML Template.
---

sudo : required
services :
    - docker
    
before_install:
    - docker build -t Abdoul-hub/test-gitactions -f Dokerfile.dev .
    
script:
    - docker run Abdoul-hub/test-gitactions
